### ISSUE TITLE
Directory structure too deep to do a git commit on Windows

### ISSUE THREAD

**Issue by brendanarnold** [gruntjs/grunt-contrib-nodeunit#27]
There is a particular file which is too deeply nested in NodeUnit for Windows to handle when doing a `git add`. The offending file is

```
node_modules/grunt-contrib-nodeunit/node_modules/nodeunit/node_modules/tap/node_modules/runforcover/node_modules/bunker/node_modules/burrito/node_modules/uglify-js/test/unit/compress/expected/array1.js
```

The potentially could be others but it causes a fatal error when running `git add -A :/`

The limit is 260 characters and is [documented here](http://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx#maxpath)

The error raised is the one discussed in [this Stackoverflow question](http://stackoverflow.com/questions/14161297/git-error-fatal-unable-to-stat-no-such-file-or-directory)

**Comment by gamicklisafisher** [comment]
I had this problem for a long time.
My friend recommended me Long Path Tool for fixing this.
