### ISSUE TITLE
Upgrade nodeunit dependency to ^0.9.1 to fix task running on node 0.12.X

### ISSUE THREAD

**Issue by Xevi** [gruntjs/grunt-contrib-nodeunit#38]
I've installed the `grunt-contrib-nodeunit` task but getting the following issue when trying to run it using `node 0.12.2`:

```
Loading "nodeunit.js" tasks...ERROR
>> Error: No such module: evals
Warning: Task "nodeunit" not found. Use --force to continue.

Aborted due to warnings.
```
Upgrading the `nodeunit` installed by the `grunt-contrib-nodeunit` task to 0.9.1 fixes the issue above.

More info in the following nodeunit [issue](https://github.com/caolan/nodeunit/issues/291)

**Comment by sindresorhus** [comment]
You will get it automatically by reinstalling this task.

https://nodesource.com/blog/semver-tilde-and-caret

**Comment by Xevi** [comment]
Ok thanks mil :)
