### ISSUE TITLE
test only one--grunt nodeunit:all:sometest

### ISSUE THREAD

**Issue by kerrer** [gruntjs/grunt-contrib-nodeunit#42]
-  grunt.registerMultiTask('nodeunit', 'Run Nodeunit unit tests.', function() {
+   grunt.registerMultiTask('nodeunit', 'Run Nodeunit unit tests.', function(testName) {
     var done = this.async();
 
     // Merge task-specific and/or target-specific options with these defaults.
@@ -282,6 +283,10 @@ module.exports = function(grunt) {
       grunt.file.mkdir(path.normalize(options.reporterOptions.output));
     }
 
+       if (testName){
+        options.reporterOptions['testspec']= testName;         
+       }

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)
